
set( XRT "${TARGET_SOURCE_DIR_TRUE}/" )

list( APPEND XSRC 
	${XRT}../engines/ccgost/e_gost_err.c
	${XRT}../engines/ccgost/gost2001.c
	${XRT}../engines/ccgost/gost2001_keyx.c
	${XRT}../engines/ccgost/gost89.c
	${XRT}../engines/ccgost/gost94_keyx.c
	${XRT}../engines/ccgost/gosthash.c
	${XRT}../engines/ccgost/gost_ameth.c
	${XRT}../engines/ccgost/gost_asn1.c
	${XRT}../engines/ccgost/gost_crypt.c
	${XRT}../engines/ccgost/gost_ctl.c
	${XRT}../engines/ccgost/gost_eng.c
	${XRT}../engines/ccgost/gost_keywrap.c
	${XRT}../engines/ccgost/gost_md.c
	${XRT}../engines/ccgost/gost_params.c
	${XRT}../engines/ccgost/gost_pmeth.c
	${XRT}../engines/ccgost/gost_sign.c
	${XRT}../engines/e_4758cca.c
	${XRT}../engines/e_aep.c
	${XRT}../engines/e_atalla.c
	${XRT}../engines/e_capi.c
	${XRT}../engines/e_chil.c
	${XRT}../engines/e_cswift.c
	${XRT}../engines/e_gmp.c
	${XRT}../engines/e_nuron.c
	${XRT}../engines/e_padlock.c
	${XRT}../engines/e_sureware.c
	${XRT}../engines/e_ubsec.c
)

list( APPEND XSRC 
  ${XRT}cpt_err.c
  ${XRT}cryptlib.c
  ${XRT}cversion.c
	${XRT}aes/aes_cbc.c
	${XRT}aes/aes_cfb.c
	${XRT}aes/aes_core.c
	${XRT}aes/aes_ctr.c
	${XRT}aes/aes_ecb.c
	${XRT}aes/aes_ige.c
	${XRT}aes/aes_misc.c
	${XRT}aes/aes_ofb.c
	${XRT}aes/aes_wrap.c
	${XRT}asn1/ameth_lib.c
	${XRT}asn1/asn1_err.c
	${XRT}asn1/asn1_gen.c
	${XRT}asn1/asn1_lib.c
	${XRT}asn1/asn1_mac.h
	${XRT}asn1/asn1_par.c
	${XRT}asn1/asn_mime.c
	${XRT}asn1/asn_moid.c
	${XRT}asn1/asn_pack.c
	${XRT}asn1/a_bitstr.c
	${XRT}asn1/a_bool.c
	${XRT}asn1/a_bytes.c
	${XRT}asn1/a_d2i_fp.c
	${XRT}asn1/a_digest.c
	${XRT}asn1/a_dup.c
	${XRT}asn1/a_enum.c
	${XRT}asn1/a_gentm.c
	${XRT}asn1/a_i2d_fp.c
	${XRT}asn1/a_int.c
	${XRT}asn1/a_mbstr.c
	${XRT}asn1/a_object.c
	${XRT}asn1/a_octet.c
	${XRT}asn1/a_print.c
	${XRT}asn1/a_set.c
	${XRT}asn1/a_sign.c
	${XRT}asn1/a_strex.c
	${XRT}asn1/a_strnid.c
	${XRT}asn1/a_time.c
	${XRT}asn1/a_type.c
	${XRT}asn1/a_utctm.c
	${XRT}asn1/a_utf8.c
	${XRT}asn1/a_verify.c
	${XRT}asn1/bio_asn1.c
	${XRT}asn1/bio_ndef.c
	${XRT}asn1/d2i_pr.c
	${XRT}asn1/d2i_pu.c
	${XRT}asn1/evp_asn1.c
	${XRT}asn1/f_enum.c
	${XRT}asn1/f_int.c
	${XRT}asn1/f_string.c
	${XRT}asn1/i2d_pr.c
	${XRT}asn1/i2d_pu.c
	${XRT}asn1/nsseq.c
	${XRT}asn1/n_pkey.c
	${XRT}asn1/p5_pbe.c
	${XRT}asn1/p5_pbev2.c
	${XRT}asn1/p8_pkey.c
	${XRT}asn1/tasn_dec.c
	${XRT}asn1/tasn_enc.c
	${XRT}asn1/tasn_fre.c
	${XRT}asn1/tasn_new.c
	${XRT}asn1/tasn_prn.c
	${XRT}asn1/tasn_typ.c
	${XRT}asn1/tasn_utl.c
	${XRT}asn1/t_bitst.c
	${XRT}asn1/t_crl.c
	${XRT}asn1/t_pkey.c
	${XRT}asn1/t_req.c
	${XRT}asn1/t_spki.c
	${XRT}asn1/t_x509.c
	${XRT}asn1/t_x509a.c
	${XRT}asn1/x_algor.c
	${XRT}asn1/x_attrib.c
	${XRT}asn1/x_bignum.c
	${XRT}asn1/x_crl.c
	${XRT}asn1/x_exten.c
	${XRT}asn1/x_info.c
	${XRT}asn1/x_long.c
	${XRT}asn1/x_name.c
	${XRT}asn1/x_nx509.c
	${XRT}asn1/x_pkey.c
	${XRT}asn1/x_pubkey.c
	${XRT}asn1/x_req.c
	${XRT}asn1/x_sig.c
	${XRT}asn1/x_spki.c
	${XRT}asn1/x_val.c
	${XRT}asn1/x_x509.c
	${XRT}asn1/x_x509a.c
	${XRT}bf/bf_cfb64.c
	${XRT}bf/bf_ecb.c
	${XRT}bf/bf_enc.c
	${XRT}bf/bf_ofb64.c
	${XRT}bf/bf_skey.c
	${XRT}bio/bf_buff.c
	${XRT}bio/bf_lbuf.c
	${XRT}bio/bf_nbio.c
	${XRT}bio/bf_null.c
	${XRT}bio/bio_cb.c
	${XRT}bio/bio_err.c
	${XRT}bio/bio_lib.c
	${XRT}bio/bss_acpt.c
	${XRT}bio/bss_bio.c
	${XRT}bio/bss_conn.c
	${XRT}bio/bss_dgram.c
	${XRT}bio/bss_fd.c
	${XRT}bio/bss_file.c
	${XRT}bio/bss_log.c
	${XRT}bio/bss_mem.c
	${XRT}bio/bss_null.c
	${XRT}bio/bss_sock.c
	${XRT}bio/b_dump.c
	${XRT}bio/b_print.c
	${XRT}bio/b_sock.c
	${XRT}bn/bn_add.c
	${XRT}bn/bn_asm.c
	${XRT}bn/bn_blind.c
	${XRT}bn/bn_const.c
	${XRT}bn/bn_ctx.c
	${XRT}bn/bn_depr.c
	${XRT}bn/bn_div.c
	${XRT}bn/bn_err.c
	${XRT}bn/bn_exp.c
	${XRT}bn/bn_exp2.c
	${XRT}bn/bn_gcd.c
	${XRT}bn/bn_gf2m.c
	${XRT}bn/bn_kron.c
	${XRT}bn/bn_lib.c
	${XRT}bn/bn_mod.c
	${XRT}bn/bn_mont.c
	${XRT}bn/bn_mpi.c
	${XRT}bn/bn_mul.c
	${XRT}bn/bn_nist.c
	${XRT}bn/bn_prime.c
	${XRT}bn/bn_print.c
	${XRT}bn/bn_rand.c
	${XRT}bn/bn_recp.c
	${XRT}bn/bn_shift.c
	${XRT}bn/bn_sqr.c
	${XRT}bn/bn_sqrt.c
	${XRT}bn/bn_word.c
	${XRT}buffer/buffer.c
	${XRT}buffer/buf_err.c
	${XRT}buffer/buf_str.c
	${XRT}camellia/camellia.c
	${XRT}camellia/cmll_cbc.c
	${XRT}camellia/cmll_cfb.c
	${XRT}camellia/cmll_ctr.c
	${XRT}camellia/cmll_ecb.c
	${XRT}camellia/cmll_misc.c
	${XRT}camellia/cmll_ofb.c
	${XRT}camellia/cmll_utl.c
	${XRT}cast/c_cfb64.c
	${XRT}cast/c_ecb.c
	${XRT}cast/c_enc.c
	${XRT}cast/c_ofb64.c
	${XRT}cast/c_skey.c
	${XRT}cmac/cmac.c
	${XRT}cmac/cm_ameth.c
	${XRT}cmac/cm_pmeth.c
	${XRT}cms/cms_asn1.c
	${XRT}cms/cms_att.c
	${XRT}cms/cms_cd.c
	${XRT}cms/cms_dd.c
	${XRT}cms/cms_enc.c
	${XRT}cms/cms_env.c
	${XRT}cms/cms_err.c
	${XRT}cms/cms_ess.c
	${XRT}cms/cms_io.c
	${XRT}cms/cms_kari.c
	${XRT}cms/cms_lib.c
	${XRT}cms/cms_pwri.c
	${XRT}cms/cms_sd.c
	${XRT}cms/cms_smime.c
	${XRT}comp/comp_err.c
	${XRT}comp/comp_lib.c
	${XRT}comp/c_rle.c
	${XRT}comp/c_zlib.c
	${XRT}conf/conf_api.c
	${XRT}conf/conf_api.h
	${XRT}conf/conf_def.c
	${XRT}conf/conf_err.c
	${XRT}conf/conf_lib.c
	${XRT}conf/conf_mall.c
	${XRT}conf/conf_mod.c
	${XRT}conf/conf_sap.c
	${XRT}des/cbc_cksm.c
	${XRT}des/cbc_enc.c
	${XRT}des/cfb64ede.c
	${XRT}des/cfb64enc.c
	${XRT}des/cfb_enc.c
	${XRT}des/des_enc.c
	${XRT}des/des_old.c
	${XRT}des/des_old2.c
	${XRT}des/ecb3_enc.c
	${XRT}des/ecb_enc.c
	${XRT}des/ede_cbcm_enc.c
	${XRT}des/enc_read.c
	${XRT}des/enc_writ.c
	${XRT}des/fcrypt.c
	${XRT}des/fcrypt_b.c
	${XRT}des/ofb64ede.c
	${XRT}des/ofb64enc.c
	${XRT}des/ofb_enc.c
	${XRT}des/pcbc_enc.c
	${XRT}des/qud_cksm.c
	${XRT}des/rand_key.c
	${XRT}des/read2pwd.c
	${XRT}des/rpc_enc.c
	${XRT}des/set_key.c
	${XRT}des/str2key.c
	${XRT}des/xcbc_enc.c
	${XRT}dh/dh_ameth.c
	${XRT}dh/dh_asn1.c
	${XRT}dh/dh_check.c
	${XRT}dh/dh_depr.c
	${XRT}dh/dh_err.c
	${XRT}dh/dh_gen.c
	${XRT}dh/dh_kdf.c
	${XRT}dh/dh_key.c
	${XRT}dh/dh_lib.c
	${XRT}dh/dh_pmeth.c
	${XRT}dh/dh_prn.c
	${XRT}dh/dh_rfc5114.c
	${XRT}dsa/dsa_ameth.c
	${XRT}dsa/dsa_asn1.c
	${XRT}dsa/dsa_depr.c
	${XRT}dsa/dsa_err.c
	${XRT}dsa/dsa_gen.c
	${XRT}dsa/dsa_key.c
	${XRT}dsa/dsa_lib.c
	${XRT}dsa/dsa_ossl.c
	${XRT}dsa/dsa_pmeth.c
	${XRT}dsa/dsa_prn.c
	${XRT}dsa/dsa_sign.c
	${XRT}dsa/dsa_vrf.c
	${XRT}dso/dso_beos.c
	${XRT}dso/dso_dl.c
	${XRT}dso/dso_dlfcn.c
	${XRT}dso/dso_err.c
	${XRT}dso/dso_lib.c
	${XRT}dso/dso_null.c
	${XRT}dso/dso_openssl.c
	${XRT}dso/dso_vms.c
	${XRT}dso/dso_win32.c
	${XRT}ebcdic.c
	${XRT}ec/ec2_mult.c
	${XRT}ec/ec2_oct.c
	${XRT}ec/ec2_smpl.c
	${XRT}ec/eck_prn.c
	${XRT}ec/ecp_mont.c
	${XRT}ec/ecp_nist.c
	${XRT}ec/ecp_oct.c
	${XRT}ec/ecp_smpl.c
	${XRT}ec/ec_ameth.c
	${XRT}ec/ec_asn1.c
	${XRT}ec/ec_check.c
	${XRT}ec/ec_curve.c
	${XRT}ec/ec_cvt.c
	${XRT}ec/ec_err.c
	${XRT}ec/ec_key.c
	${XRT}ec/ec_lib.c
	${XRT}ec/ec_mult.c
	${XRT}ec/ec_oct.c
	${XRT}ec/ec_pmeth.c
	${XRT}ec/ec_print.c
	${XRT}ecdh/ech_err.c
	${XRT}ecdh/ech_kdf.c
	${XRT}ecdh/ech_key.c
	${XRT}ecdh/ech_lib.c
	${XRT}ecdh/ech_ossl.c
	${XRT}ecdsa/ecs_asn1.c
	${XRT}ecdsa/ecs_err.c
	${XRT}ecdsa/ecs_lib.c
	${XRT}ecdsa/ecs_ossl.c
	${XRT}ecdsa/ecs_sign.c
	${XRT}ecdsa/ecs_vrf.c
	${XRT}engine/eng_all.c
	${XRT}engine/eng_cnf.c
	${XRT}engine/eng_cryptodev.c
	${XRT}engine/eng_ctrl.c
	${XRT}engine/eng_dyn.c
	${XRT}engine/eng_err.c
	${XRT}engine/eng_fat.c
	${XRT}engine/eng_init.c
	${XRT}engine/eng_lib.c
	${XRT}engine/eng_list.c
	${XRT}engine/eng_openssl.c
	${XRT}engine/eng_pkey.c
	${XRT}engine/eng_rdrand.c
	${XRT}engine/eng_table.c
	${XRT}engine/tb_asnmth.c
	${XRT}engine/tb_cipher.c
	${XRT}engine/tb_dh.c
	${XRT}engine/tb_digest.c
	${XRT}engine/tb_dsa.c
	${XRT}engine/tb_ecdh.c
	${XRT}engine/tb_ecdsa.c
	${XRT}engine/tb_pkmeth.c
	${XRT}engine/tb_rand.c
	${XRT}engine/tb_rsa.c
	${XRT}engine/tb_store.c
	${XRT}err/err.c
	${XRT}err/err_all.c
	${XRT}err/err_prn.c
	${XRT}evp/bio_b64.c
	${XRT}evp/bio_enc.c
	${XRT}evp/bio_md.c
	${XRT}evp/bio_ok.c
	${XRT}evp/c_all.c
	${XRT}evp/c_allc.c
	${XRT}evp/c_alld.c
	${XRT}evp/digest.c
	${XRT}evp/encode.c
	${XRT}evp/evp_acnf.c
	${XRT}evp/evp_cnf.c
	${XRT}evp/evp_enc.c
	${XRT}evp/evp_err.c
	${XRT}evp/evp_key.c
	${XRT}evp/evp_lib.c
	${XRT}evp/evp_pbe.c
	${XRT}evp/evp_pkey.c
	${XRT}evp/e_aes.c
	${XRT}evp/e_aes_cbc_hmac_sha1.c
	${XRT}evp/e_aes_cbc_hmac_sha256.c
	${XRT}evp/e_bf.c
	${XRT}evp/e_camellia.c
	${XRT}evp/e_cast.c
	${XRT}evp/e_des.c
	${XRT}evp/e_des3.c
	${XRT}evp/e_idea.c
	${XRT}evp/e_null.c
	${XRT}evp/e_old.c
	${XRT}evp/e_rc2.c
	${XRT}evp/e_rc4.c
	${XRT}evp/e_rc4_hmac_md5.c
	${XRT}evp/e_rc5.c
	${XRT}evp/e_seed.c
	${XRT}evp/e_xcbc_d.c
	${XRT}evp/m_dss.c
	${XRT}evp/m_dss1.c
	${XRT}evp/m_ecdsa.c
	${XRT}evp/m_md2.c
	${XRT}evp/m_md4.c
	${XRT}evp/m_md5.c
	${XRT}evp/m_mdc2.c
	${XRT}evp/m_null.c
	${XRT}evp/m_ripemd.c
	${XRT}evp/m_sha.c
	${XRT}evp/m_sha1.c
	${XRT}evp/m_sigver.c
	${XRT}evp/m_wp.c
	${XRT}evp/names.c
	${XRT}evp/p5_crpt.c
	${XRT}evp/p5_crpt2.c
	${XRT}evp/pmeth_fn.c
	${XRT}evp/pmeth_gn.c
	${XRT}evp/pmeth_lib.c
	${XRT}evp/p_dec.c
	${XRT}evp/p_enc.c
	${XRT}evp/p_lib.c
	${XRT}evp/p_open.c
	${XRT}evp/p_seal.c
	${XRT}evp/p_sign.c
	${XRT}evp/p_verify.c
	${XRT}ex_data.c
	${XRT}hmac/hmac.c
	${XRT}hmac/hm_ameth.c
	${XRT}hmac/hm_pmeth.c
	${XRT}idea/i_cbc.c
	${XRT}idea/i_cfb64.c
	${XRT}idea/i_ecb.c
	${XRT}idea/i_ofb64.c
	${XRT}idea/i_skey.c
	${XRT}krb5/krb5_asn.c
	${XRT}lhash/lhash.c
	${XRT}lhash/lh_stats.c
	${XRT}md4/md4_dgst.c
	${XRT}md4/md4_one.c
	${XRT}md5/md5_dgst.c
	${XRT}md5/md5_one.c
	${XRT}mdc2/mdc2dgst.c
	${XRT}mdc2/mdc2_one.c
	${XRT}mem.c
	${XRT}mem_clr.c
	${XRT}mem_dbg.c
	${XRT}modes/cbc128.c
	${XRT}modes/ccm128.c
	${XRT}modes/cfb128.c
	${XRT}modes/ctr128.c
	${XRT}modes/cts128.c
	${XRT}modes/gcm128.c
	${XRT}modes/ofb128.c
	${XRT}modes/wrap128.c
	${XRT}modes/xts128.c
	${XRT}objects/obj_dat.c
	${XRT}objects/obj_err.c
	${XRT}objects/obj_lib.c
	${XRT}objects/obj_xref.c
	${XRT}objects/o_names.c
	${XRT}ocsp/ocsp_asn.c
	${XRT}ocsp/ocsp_cl.c
	${XRT}ocsp/ocsp_err.c
	${XRT}ocsp/ocsp_ext.c
	${XRT}ocsp/ocsp_ht.c
	${XRT}ocsp/ocsp_lib.c
	${XRT}ocsp/ocsp_prn.c
	${XRT}ocsp/ocsp_srv.c
	${XRT}ocsp/ocsp_vfy.c
	${XRT}o_dir.c
	${XRT}o_init.c
	${XRT}o_str.c
	${XRT}o_time.c
	${XRT}pem/pem_all.c
	${XRT}pem/pem_err.c
	${XRT}pem/pem_info.c
	${XRT}pem/pem_lib.c
	${XRT}pem/pem_oth.c
	${XRT}pem/pem_pk8.c
	${XRT}pem/pem_pkey.c
	${XRT}pem/pem_seal.c
	${XRT}pem/pem_sign.c
	${XRT}pem/pem_x509.c
	${XRT}pem/pem_xaux.c
	${XRT}pem/pvkfmt.c
	${XRT}pkcs12/p12_add.c
	${XRT}pkcs12/p12_asn.c
	${XRT}pkcs12/p12_attr.c
	${XRT}pkcs12/p12_crpt.c
	${XRT}pkcs12/p12_crt.c
	${XRT}pkcs12/p12_decr.c
	${XRT}pkcs12/p12_init.c
	${XRT}pkcs12/p12_key.c
	${XRT}pkcs12/p12_kiss.c
	${XRT}pkcs12/p12_mutl.c
	${XRT}pkcs12/p12_npas.c
	${XRT}pkcs12/p12_p8d.c
	${XRT}pkcs12/p12_p8e.c
	${XRT}pkcs12/p12_utl.c
	${XRT}pkcs12/pk12err.c
	${XRT}pkcs7/bio_pk7.c
	${XRT}pkcs7/pk7_asn1.c
	${XRT}pkcs7/pk7_attr.c
	${XRT}pkcs7/pk7_doit.c
	${XRT}pkcs7/pk7_lib.c
	${XRT}pkcs7/pk7_mime.c
	${XRT}pkcs7/pk7_smime.c
	${XRT}pkcs7/pkcs7err.c
	${XRT}pqueue/pqueue.c
	${XRT}rand/md_rand.c
	${XRT}rand/randfile.c
	${XRT}rand/rand_egd.c
	${XRT}rand/rand_err.c
	${XRT}rand/rand_lib.c
	${XRT}rand/rand_nw.c
	${XRT}rand/rand_os2.c
	${XRT}rand/rand_unix.c
	${XRT}rand/rand_win.c
	${XRT}rc2/rc2cfb64.c
	${XRT}rc2/rc2ofb64.c
	${XRT}rc2/rc2_cbc.c
	${XRT}rc2/rc2_ecb.c
	${XRT}rc2/rc2_skey.c
	${XRT}rc4/rc4_enc.c
	${XRT}rc4/rc4_skey.c
	${XRT}rc4/rc4_utl.c
	${XRT}rc5/rc5cfb64.c
	${XRT}rc5/rc5ofb64.c
	${XRT}rc5/rc5_ecb.c
	${XRT}rc5/rc5_enc.c
	${XRT}rc5/rc5_skey.c
	${XRT}ripemd/rmd_dgst.c
	${XRT}ripemd/rmd_one.c
	${XRT}rsa/rsa_ameth.c
	${XRT}rsa/rsa_asn1.c
	${XRT}rsa/rsa_chk.c
	${XRT}rsa/rsa_crpt.c
	${XRT}rsa/rsa_depr.c
	${XRT}rsa/rsa_eay.c
	${XRT}rsa/rsa_err.c
	${XRT}rsa/rsa_gen.c
	${XRT}rsa/rsa_lib.c
	${XRT}rsa/rsa_none.c
	${XRT}rsa/rsa_null.c
	${XRT}rsa/rsa_oaep.c
	${XRT}rsa/rsa_pk1.c
	${XRT}rsa/rsa_pmeth.c
	${XRT}rsa/rsa_prn.c
	${XRT}rsa/rsa_pss.c
	${XRT}rsa/rsa_saos.c
	${XRT}rsa/rsa_sign.c
	${XRT}rsa/rsa_ssl.c
	${XRT}rsa/rsa_x931.c
	${XRT}seed/seed.c
	${XRT}seed/seed_cbc.c
	${XRT}seed/seed_cfb.c
	${XRT}seed/seed_ecb.c
	${XRT}seed/seed_ofb.c
	${XRT}sha/sha1dgst.c
	${XRT}sha/sha1_one.c
	${XRT}sha/sha256.c
	${XRT}sha/sha512.c
	${XRT}sha/sha_dgst.c
	${XRT}sha/sha_one.c
	${XRT}srp/srp_lib.c
	${XRT}srp/srp_vfy.c
	${XRT}stack/stack.c
	${XRT}ts/ts_asn1.c
	${XRT}ts/ts_conf.c
	${XRT}ts/ts_err.c
	${XRT}ts/ts_lib.c
	${XRT}ts/ts_req_print.c
	${XRT}ts/ts_req_utils.c
	${XRT}ts/ts_rsp_print.c
	${XRT}ts/ts_rsp_sign.c
	${XRT}ts/ts_rsp_utils.c
	${XRT}ts/ts_rsp_verify.c
	${XRT}ts/ts_verify_ctx.c
	${XRT}txt_db/txt_db.c
	${XRT}ui/ui_compat.c
	${XRT}ui/ui_err.c
	${XRT}ui/ui_lib.c
	${XRT}ui/ui_openssl.c
	${XRT}ui/ui_util.c
	${XRT}uid.c
	${XRT}whrlpool/wp_block.c
	${XRT}whrlpool/wp_dgst.c
	${XRT}x509/by_dir.c
	${XRT}x509/by_file.c
	${XRT}x509/x509cset.c
	${XRT}x509/x509name.c
	${XRT}x509/x509rset.c
	${XRT}x509/x509spki.c
	${XRT}x509/x509type.c
	${XRT}x509/x509_att.c
	${XRT}x509/x509_cmp.c
	${XRT}x509/x509_d2.c
	${XRT}x509/x509_def.c
	${XRT}x509/x509_err.c
	${XRT}x509/x509_ext.c
	${XRT}x509/x509_lu.c
	${XRT}x509/x509_obj.c
	${XRT}x509/x509_r2x.c
	${XRT}x509/x509_req.c
	${XRT}x509/x509_set.c
	${XRT}x509/x509_trs.c
	${XRT}x509/x509_txt.c
	${XRT}x509/x509_v3.c
	${XRT}x509/x509_vfy.c
	${XRT}x509/x509_vpm.c
	${XRT}x509/x_all.c
	${XRT}x509v3/pcy_cache.c
	${XRT}x509v3/pcy_data.c
	${XRT}x509v3/pcy_lib.c
	${XRT}x509v3/pcy_map.c
	${XRT}x509v3/pcy_node.c
	${XRT}x509v3/pcy_tree.c
	${XRT}x509v3/v3err.c
	${XRT}x509v3/v3_addr.c
	${XRT}x509v3/v3_akey.c
	${XRT}x509v3/v3_akeya.c
	${XRT}x509v3/v3_alt.c
	${XRT}x509v3/v3_asid.c
	${XRT}x509v3/v3_bcons.c
	${XRT}x509v3/v3_bitst.c
	${XRT}x509v3/v3_conf.c
	${XRT}x509v3/v3_cpols.c
	${XRT}x509v3/v3_crld.c
	${XRT}x509v3/v3_enum.c
	${XRT}x509v3/v3_extku.c
	${XRT}x509v3/v3_genn.c
	${XRT}x509v3/v3_ia5.c
	${XRT}x509v3/v3_info.c
	${XRT}x509v3/v3_int.c
	${XRT}x509v3/v3_lib.c
	${XRT}x509v3/v3_ncons.c
	${XRT}x509v3/v3_ocsp.c
	${XRT}x509v3/v3_pci.c
	${XRT}x509v3/v3_pcia.c
	${XRT}x509v3/v3_pcons.c
	${XRT}x509v3/v3_pku.c
	${XRT}x509v3/v3_pmaps.c
	${XRT}x509v3/v3_prn.c
	${XRT}x509v3/v3_purp.c
	${XRT}x509v3/v3_scts.c
	${XRT}x509v3/v3_skey.c
	${XRT}x509v3/v3_sxnet.c
	${XRT}x509v3/v3_utl.c	
)

list( APPEND XINC 
	${XRT}aes/aes.h
	${XRT}asn1/asn1.h
	${XRT}asn1/asn1t.h
	${XRT}asn1/asn1_mac.h
	${XRT}bf/blowfish.h
	${XRT}bio/bio.h
	${XRT}bn/bn.h
	${XRT}buffer/buffer.h
	${XRT}camellia/camellia.h
	${XRT}cast/cast.h
	${XRT}cmac/cmac.h
	${XRT}cms/cms.h
	${XRT}comp/comp.h	
	${XRT}conf/conf.h	
	${XRT}conf/conf_api.h	
	${XRT}des/des_old.h
	${XRT}des/des.h
	${XRT}rc4/rc4.h
	${XRT}rc5/rc5.h
	${XRT}rc2/rc2.h
	${XRT}ripemd/ripemd.h	
	${XRT}rand/rand.h
	${XRT}rsa/rsa.h
	${XRT}seed/seed.h	
	${XRT}sha/sha.h	
	${XRT}srp/srp_grps.h
	${XRT}srp/srp_lcl.h
	${XRT}srp/srp.h	
	${XRT}stack/safestack.h
	${XRT}symhacks.h			
	${XRT}pqueue/pqueue.h
	${XRT}modes/modes.h
	${XRT}objects/objects.h
	${XRT}objects/obj_mac.h
	${XRT}ocsp/ocsp.h
	${XRT}pem/pem.h
	${XRT}pem/pem2.h
	${XRT}pkcs12/pkcs12.h
	${XRT}opensslv.h
	${XRT}ossl_typ.h	
	${XRT}pkcs7/pkcs7.h
	${XRT}lhash/lhash.h
	${XRT}md4/md4.h
	${XRT}md5/md5.h
	${XRT}mdc2/mdc2.h
	${XRT}idea/idea.h
	${XRT}krb5/krb5_asn.h
	${XRT}hmac/hmac.h
	${XRT}evp/evp.h
	${XRT}err/err.h
	${XRT}engine/engine.h
	${XRT}ecdsa/ecdsa.h
	${XRT}ecdh/ecdh.h
	${XRT}ebcdic.h
	${XRT}dso/dso.h
	${XRT}dsa/dsa.h
	${XRT}x509/x509.h
	${XRT}x509/x509_vfy.h
	${XRT}x509v3/x509v3.h
	${XRT}txt_db/txt_db.h
	${XRT}ui/ui.h
	${XRT}ui/ui_compat.h
	${XRT}whrlpool/whrlpool.h	
	${XRT}ts/ts.h
	${XRT}ec/ec.h
	${XRT}dh/dh.h	
	${XRT}stack/stack.h	
	${XRT}crypto.h		
)

